# Generated by Django 2.0.5 on 2018-05-29 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='prayer_item',
        ),
        migrations.AddField(
            model_name='prayeritem',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='prayer_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayers.PrayerItem'),
        ),
    ]
