# Generated by Django 2.0.5 on 2018-05-30 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_auto_20180529_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayeritem',
            old_name='name',
            new_name='title',
        ),
    ]
