# Generated by Django 2.0.5 on 2018-06-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0003_auto_20180530_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayeritem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
