# Generated by Django 2.0.5 on 2018-06-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0004_auto_20180602_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiblePassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
